language: haskell
install:
  - "cabal install --enable-tests -v3 --dry-run -ftools"
  - "travis_retry cabal install --only-dependencies --enable-tests --force-reinstalls -ftools"
script:
  - "cabal install --jobs=1 -ftools"
notifications:
  email:
    recipients: travis@silk.co
    on_success: never
    on_failure: change
